### ISSUE TITLE
Fix scala-reflect for cross-scala support

### ISSUE THREAD

**Issue by calippo** [buildo/wiro#11]
## description
`value` can only be used within a task or setting macro.

## how to reproduce
`sbt reload`

## misc
<img width="716" alt="screen shot 2017-02-13 at 16 56 56" src="https://cloud.githubusercontent.com/assets/2476080/22893744/8c3a265c-f20e-11e6-8c81-92c92fac474e.png">

**Comment by gabro** [comment]
woops, my bad
