### ISSUE TITLE
Wiro is logging unncessary stuff

### ISSUE THREAD

**Issue by calippo** [buildo/wiro#125]
## description
Wiro is logging unncessary stuff.

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

**Comment by albertocoletta** [comment]
@calippo here's a screenshot.

<img width="1137" alt="screen shot 2018-06-11 at 12 55 41" src="https://user-images.githubusercontent.com/3520636/41228175-ba668f30-6d77-11e8-89ab-b9ee9a01c11a.png">

**Comment by gabro** [comment]
👍 to this. I would suggest to include the stacktrace only under a `debug` level.

**Comment by calippo** [comment]
@gabro the weird thing is that we're not logging the stacktrace 🙀

**Comment by gabro** [comment]
Then probably it's an uncaught exception
