### ISSUE TITLE
Support @path on controllers methods

### ISSUE THREAD

**Issue by bytecodeguru** [buildo/wiro#20]
## requirements
Support the use of `@path` on controllers' methods to override the uri path name with the following semantics:

```scala
@path("foo")
trait FooController {

  @query @path("baz")
  def bar(): Bar

  @query @path("bar/search")  // we agreed not to implement for the moment
  def barSearch(): Bar 

}
```

publishes the following routes:

```http
GET /foo/baz
GET /foo/bar/search #we agreed not to implement for the moment
```

**Comment by calippo** [comment]
@bytecodeguru 

I don't like the name - what about `operation` instead of `path`?

e.g:
```scala
@path("foo")
trait FooController {

  @query @operation("baz")
  def bar(): Bar

}
```

**Comment by calippo** [comment]
After an offline discussion we agreed on the following syntax:

```scala
@path("foo")
trait FooController {

  @query(name = "baz")
  def bar(): Bar

}
```

**Comment by bytecodeguru** [comment]
Perhaps the `name =` part it's not necessary, for consistency with `@path("foo")` it's enough to have just `@query("baz")` and `@command("bar")`

**Comment by gabro** [comment]
question: why renaming the method? It seems unnecessary. Can't you just use the metadata to route the http to the original method?

--
gabriele
~ buildo
